import type { Worker, Builder, Job } from "@/types";

export const SEED_WORKERS: Worker[] = [
  {
    id: "w-001",
    name: "Liam Hawthorne",
    photo: "https://images.unsplash.com/photo-1521119989659-a83eee488004?w=600",
    primaryTrade: "Carpentry",
    skills: ["Carpentry", "Roofing", "Flooring"],
    yearsExperience: 9,
    availableNow: true,
    suburb: "Shoreditch",
    postcode: "E1 6RF",
    distanceKm: 4,
    rating: 4.9,
    completedJobs: 31,
    bio: "Second-fix specialist. Reliable, on time, brings my own tools.",
    tickets: ["CSCS Card", "Working at Heights"],
    hourlyRate: 32,
    publicLiabilityInsured: true,
    insurerName: "Hiscox",
  },
  {
    id: "w-002",
    name: "Marcus Kelani",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600",
    primaryTrade: "Concreting",
    skills: ["Concreting", "Steel Fixing"],
    yearsExperience: 12,
    availableNow: false,
    availableFrom: "Mon 5 May",
    suburb: "Lewisham",
    postcode: "SE13 7EJ",
    distanceKm: 11,
    rating: 4.7,
    completedJobs: 58,
    bio: "Slabs, footings, decorative finishes. Crew of 3 available.",
    tickets: ["CSCS Card", "Confined Space"],
    hourlyRate: 35,
  },
  {
    id: "w-003",
    name: "Sienna Brooks",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600",
    primaryTrade: "Electrical",
    skills: ["Electrical", "HVAC"],
    yearsExperience: 6,
    availableNow: true,
    suburb: "Hackney",
    postcode: "E8 2EL",
    distanceKm: 6,
    rating: 4.8,
    completedJobs: 22,
    bio: "Qualified sparky. Residential and commercial fit-outs. 18th Edition certified.",
    tickets: ["CSCS Card", "IPAF Card"],
    hourlyRate: 40,
    publicLiabilityInsured: true,
    insurerName: "AXA",
  },
  {
    id: "w-004",
    name: "Diego Ferreira",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600",
    primaryTrade: "Bricklaying",
    skills: ["Bricklaying", "Rendering"],
    yearsExperience: 15,
    availableNow: true,
    suburb: "Bethnal Green",
    postcode: "E2 0HJ",
    distanceKm: 13,
    rating: 5.0,
    completedJobs: 74,
    bio: "Heritage restoration and modern builds. Rapid pace, high quality finish.",
    tickets: ["CSCS Card", "First Aid"],
    hourlyRate: 35,
    publicLiabilityInsured: true,
    insurerName: "Zurich",
  },
  {
    id: "w-005",
    name: "Aiyana Whitcombe",
    photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600",
    primaryTrade: "Tiling",
    skills: ["Tiling", "Waterproofing"],
    yearsExperience: 7,
    availableNow: false,
    availableFrom: "Wed 14 May",
    suburb: "Southwark",
    postcode: "SE1 4RS",
    distanceKm: 3,
    rating: 4.6,
    completedJobs: 19,
    bio: "Bathrooms, kitchens, large-format tiles. Tanking and waterproof membrane certified.",
    tickets: ["CSCS Card", "Asbestos Awareness"],
    hourlyRate: 30,
  },
  {
    id: "w-006",
    name: "Jonas Petrov",
    photo: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600",
    primaryTrade: "Plumbing",
    skills: ["Plumbing", "Welding"],
    yearsExperience: 10,
    availableNow: true,
    suburb: "Bermondsey",
    postcode: "SE1 3UH",
    distanceKm: 5,
    rating: 4.9,
    completedJobs: 44,
    bio: "Hot water, gas, drainage. Gas Safe registered. Emergency call-outs accepted.",
    tickets: ["CSCS Card", "Confined Space", "First Aid"],
    hourlyRate: 42,
    publicLiabilityInsured: true,
    insurerName: "Simply Business",
  },
];

export const SEED_BUILDERS: Builder[] = [
  {
    id: "b-001",
    name: "Northline Build Co",
    contactName: "Aaron Voss",
    photo: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600",
    suburb: "Islington",
    postcode: "N1 9GU",
    rating: 4.7,
    completedJobs: 89,
    bio: "Commercial fit-outs across inner London. Crews of 2–8.",
    tradesNeeded: ["Carpentry", "Electrical", "Plumbing"],
  },
  {
    id: "b-002",
    name: "Oakridge Homes",
    contactName: "Priya Mehta",
    photo: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600",
    suburb: "Kensington",
    postcode: "W8 4PY",
    rating: 4.9,
    completedJobs: 142,
    bio: "Custom luxury residential. Long-term subcontractor relationships.",
    tradesNeeded: ["Bricklaying", "Tiling", "Carpentry", "Painting"],
  },
  {
    id: "b-003",
    name: "Harbour Civil Group",
    contactName: "Tom Reeves",
    photo: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600",
    suburb: "Canary Wharf",
    postcode: "E14 5AB",
    rating: 4.5,
    completedJobs: 67,
    bio: "Civil and infrastructure. Steady pipeline of multi-week work.",
    tradesNeeded: ["Concreting", "Steel Fixing", "Excavation"],
  },
];

export const SEED_JOBS: Job[] = [
  {
    id: "j-001",
    builderId: "b-001",
    title: "Second-fix carpenter — Shoreditch bar fit-out",
    trade: "Carpentry",
    suburb: "Shoreditch",
    postcode: "E1 6RF",
    startDate: "Mon 28 Apr",
    durationDays: 12,
    payRate: 35,
    payType: "hour",
    requiredTickets: ["CSCS Card"],
    description:
      "Full second-fix on a 220sqm bar. Joinery installs, doors, skirtings, decorative timber feature wall. Tools and materials supplied.",
    createdAt: Date.now() - 1000 * 60 * 60 * 4,
    applicants: [],
  },
  {
    id: "j-002",
    builderId: "b-002",
    title: "Slab pour crew — Kensington new build",
    trade: "Concreting",
    suburb: "Kensington",
    postcode: "W8 4PY",
    startDate: "Sat 3 May",
    durationDays: 1,
    payRate: 420,
    payType: "day",
    requiredTickets: ["CSCS Card", "Confined Space"],
    description:
      "Single-day pour for ground-floor slab on luxury residential build. Need 3–4 experienced concreters. Pump truck arrives 6am.",
    createdAt: Date.now() - 1000 * 60 * 60 * 26,
    applicants: [],
  },
  {
    id: "j-003",
    builderId: "b-003",
    title: "Steel fixer — Canary Wharf mid-rise",
    trade: "Steel Fixing",
    suburb: "Canary Wharf",
    postcode: "E14 5AB",
    startDate: "Mon 12 May",
    durationDays: 28,
    payRate: 40,
    payType: "hour",
    requiredTickets: ["CSCS Card", "Working at Heights"],
    description:
      "Floors 4–7 of mid-rise residential development. Reading drawings essential. Clean site, secure parking on-site.",
    createdAt: Date.now() - 1000 * 60 * 60 * 50,
    applicants: [],
  },
  {
    id: "j-004",
    builderId: "b-001",
    title: "Qualified electrician — commercial office fit-out",
    trade: "Electrical",
    suburb: "Islington",
    postcode: "N1 9GU",
    startDate: "Wed 30 Apr",
    durationDays: 5,
    payRate: 45,
    payType: "hour",
    requiredTickets: ["CSCS Card", "IPAF Card"],
    description:
      "Lighting circuits, sockets, consumer unit upgrades for a small office space. EICRs and completion certs required.",
    createdAt: Date.now() - 1000 * 60 * 60 * 8,
    applicants: [],
  },
];
