// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/app-icons/ArchBridge.tsx": () => import("../components/mockups/app-icons/ArchBridge.tsx"),
  "./components/mockups/app-icons/Blueprint.tsx": () => import("../components/mockups/app-icons/Blueprint.tsx"),
  "./components/mockups/app-icons/Crane.tsx": () => import("../components/mockups/app-icons/Crane.tsx"),
  "./components/mockups/app-icons/GeometricMark.tsx": () => import("../components/mockups/app-icons/GeometricMark.tsx"),
  "./components/mockups/app-icons/HardHatBolt.tsx": () => import("../components/mockups/app-icons/HardHatBolt.tsx"),
  "./components/mockups/app-icons/Monogram.tsx": () => import("../components/mockups/app-icons/Monogram.tsx"),
  "./components/mockups/app-icons/ShieldCraft.tsx": () => import("../components/mockups/app-icons/ShieldCraft.tsx"),
  "./components/mockups/app-icons/SwipeMatch.tsx": () => import("../components/mockups/app-icons/SwipeMatch.tsx"),
  "./components/mockups/app-icons/TwoWorkers.tsx": () => import("../components/mockups/app-icons/TwoWorkers.tsx"),
  "./components/mockups/app-icons/WeldSpark.tsx": () => import("../components/mockups/app-icons/WeldSpark.tsx"),
  "./components/mockups/font-options/BarlowSemiCondensed.tsx": () => import("../components/mockups/font-options/BarlowSemiCondensed.tsx"),
  "./components/mockups/font-options/PlusJakartaSans.tsx": () => import("../components/mockups/font-options/PlusJakartaSans.tsx"),
  "./components/mockups/font-options/Syne.tsx": () => import("../components/mockups/font-options/Syne.tsx"),
  "./components/mockups/font-options/Urbanist.tsx": () => import("../components/mockups/font-options/Urbanist.tsx"),
  "./components/mockups/buildmatch-palettes/Cinnabar.tsx": () => import("../components/mockups/buildmatch-palettes/Cinnabar.tsx"),
  "./components/mockups/buildmatch-palettes/Forest.tsx": () => import("../components/mockups/buildmatch-palettes/Forest.tsx"),
  "./components/mockups/buildmatch-palettes/LightTheme.tsx": () => import("../components/mockups/buildmatch-palettes/LightTheme.tsx"),
  "./components/mockups/buildmatch-palettes/Original.tsx": () => import("../components/mockups/buildmatch-palettes/Original.tsx"),
  "./components/mockups/buildmatch-palettes/SteelBlue.tsx": () => import("../components/mockups/buildmatch-palettes/SteelBlue.tsx")
};
